### ISSUE TITLE
Add outcomes column

### ISSUE THREAD

**Issue by saarnilauri** [saarnilauri/fida-imu#65]
As an admin, I want to add outcomes to the results chain.

![outcome-col.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a95184c71e2d90011108a39/125516c66e82c728ace21e0d46e7818e208d8eacc2eab04fe611b2843b492d762a10e17132d0ba2eee412d555d5b1af9470d5a44fcf0dd2da4be6e238f4e17ff933c0120996048e6edc00db513bb27814e80b4ba8844c2eb3427ef8c865d73.png)

**Comment by laurisaarni** [comment]
Has been closed already with earlier work.
